# network_CNN.yaml file

Network:
  epochs: 50
  batch_size: 10
  n_steps: 5
  dataset: "CIFAR10"
  SpikeBasedBPTT: True
  lr: 0.00005

Layers:
  conv_1:
    type: "convspiking"   # 32*32  28*28
    in_channels: 3
    out_channels: 96
    kernel_size: 3
    weight_scale: 5
    padding: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  conv_2:
    type: "convspiking" # 32*32  28*28
    in_channels: 96
    out_channels: 256
    kernel_size: 3
    weight_scale: 5
    padding: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  pooling_1:
    type: "pooling"
    kernel_size: 2
    tau_m: 8
    tau_s: 2
    threshold: 1

  conv_3:
    type: "convspiking" # 16*16  14*14
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    weight_scale: 5
    padding: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  pooling_2:
    type: "pooling"
    kernel_size: 2
    tau_m: 8
    tau_s: 2
    threshold: 1

  conv_4:
    type: "convspiking"  # 8*8  7*7
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    weight_scale: 5
    padding: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  conv_5:
    type: "convspiking"  # 8*8  7*7
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    weight_scale: 5
    padding: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  FC_1:
    type: "linear"
    n_inputs: 16384
    n_outputs: 1024
    weight_scale: 5
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm1d: False

  FC_2:
    type: "linear"
    n_inputs: 1024
    n_outputs: 1024
    weight_scale: 5
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm1d: False

  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    weight_scale: 5
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm1d: False

