# network_CNN.yaml file

Network:
  epochs: 100
  batch_size: 10
  n_steps: 5
  dataset: "MNIST"
  SpikeBasedBPTT: True
  lr: 0.0005

Layers:
  conv_1:
    type: "convspiking"
    in_channels: 1
    out_channels: 15
    kernel_size: 5
    weight_scale: 1
    padding: 0
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  pooling_1:
    type: "pooling"
    kernel_size: 2
    tau_m: 8
    tau_s: 2
    threshold: 1

  conv_2:
    type: "convspiking"
    in_channels: 15
    out_channels: 40
    kernel_size: 5
    weight_scale: 1
    padding: 0
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm3d: False

  pooling_2:
    type: "pooling"
    kernel_size: 2
    tau_m: 8
    tau_s: 2
    threshold: 1

  FC_1:
    type: "linear"
    n_inputs: 640
    n_outputs: 300
    weight_scale: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm1d: False

  output:
    type: "linear"
    n_inputs: 300
    n_outputs: 10
    weight_scale: 1
    tau_m: 8
    tau_s: 2
    threshold: 1
    batch_norm1d: False

